export const ROUTE = {
  ROOT: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "forgot-password",
  VERIFY_CODE: "verify-code",
  SET_PASSWORD: "set-password",
  NEWS: "news",
  NOT_FOUND: "*",
  SETTINGS: "settings",
  PROFILE: "profile",
  BOARDING_HOUSE: "boarding-house",
  REGISTER_TO_BECOME: "register-to-become",
  UNDER_REVIEW: "under-review",
};
